export const ITEM_NAMES = {
    log_birch: 'Birch Logs',
    log_pine: 'Pine Logs',
    log_poplar: 'Poplar Logs',
    log_alder: 'Alder Logs',
    log_cedar: 'Cedar Logs',
    log_elm: 'Elm Logs',
    log_chestnut: 'Chestnut Logs',
    log_beech: 'Beech Logs',
    log_ash: 'Ash Logs',
    log_walnut: 'Walnut Logs',
    log_sycamore: 'Sycamore Logs',
    log_hornbeam: 'Hornbeam Logs',
    log_yew: 'Yew Logs',
    log_cherry: 'Cherry Logs',
    log_ebony: 'Ebony Logs',
    log_olive: 'Olive Logs',
    log_ironwood: 'Ironwood Logs',
    log_black_locust: 'Black Locust Logs',
    log_dragonfir: 'Dragonfir Logs',
    log_world_oak: 'World Oak Logs',
    log_oak: 'Oak Logs',
    log_willow: 'Willow Logs',
    log_maple: 'Maple Logs',

    // -- SCAVENGING ITEMS --
    // TIER 1
    scrap_metal_bits: 'Scrap Metal Bits',
    frayed_wire: 'Frayed Wire',
    plastic_shards: 'Plastic Shards',
    rusted_bolt: 'Rusted Bolt',
    bent_spoon: 'Bent Spoon',
    lost_coin: 'Lost Coin',
    stone_fragments: 'Stone Fragments',
    cracked_tile: 'Cracked Tile',
    rusted_nails: 'Rusted Nails',
    broken_tool_handle: 'Broken Tool Handle',
    intact_brick: 'Intact Brick',
    small_gem_chip: 'Small Gem Chip',

    // TIER 2
    scrap_metal_plate: 'Scrap Metal Plate',
    copper_wire: 'Copper Wire',
    gear_fragment: 'Gear Fragment',
    small_spring: 'Small Spring',
    intact_gear: 'Intact Gear',
    broken_servo: 'Broken Servo',
    slick_sludge: 'Slick Sludge',
    waterlogged_scrap: 'Waterlogged Scrap',
    moldy_cloth: 'Moldy Cloth',
    corroded_battery: 'Corroded Battery',
    intact_fuse: 'Intact Fuse',
    old_pendant: 'Old Pendant',
    mixed_scrap: 'Mixed Scrap',
    glass_shards: 'Glass Shards',
    metal_pipe_chunk: 'Metal Pipe Chunk',
    broken_circuit_board: 'Broken Circuit Board',
    intact_container: 'Intact Container',
    ancient_coin: 'Ancient Coin',
    recovered_trinket: 'Recovered Trinket',

    // NEW SCAVENGING ITEMS
    camera_lens: 'Camera Lens',
    small_battery: 'Small Battery',
    concrete_chunk: 'Concrete Chunk',
    rebar_fragment: 'Rebar Fragment',
    old_rations: 'Old Rations',
    ammo_casing: 'Ammo Casing',
    plasma_residue: 'Plasma Residue',
    burnt_coil: 'Burnt Coil',
    heat_sink: 'Heat Sink',
    satellite_dish: 'Satellite Dish',
    solar_panel_shard: 'Solar Panel Shard',
    vacuum_sealed_pouch: 'Vacuum Pouch',
    cosmic_dust: 'Cosmic Dust',
    alien_glyph: 'Alien Glyph',
    unknown_alloy: 'Unknown Alloy',
    singularity_shards: 'Singularity Shards',

    // TIER 3
    wood_scraps: 'Wood Scraps',
    rusted_hinges: 'Rusted Hinges',
    fabric_scraps: 'Fabric Scraps',
    intact_lock: 'Intact Lock',
    polished_stone: 'Polished Stone',
    old_journal_page: 'Old Journal Page',
    strange_key: 'Strange Key',
    metal_panel: 'Metal Panel',
    wire_bundle: 'Wire Bundle',
    reinforced_bolts: 'Reinforced Bolts',
    structural_beam_piece: 'Structural Beam Piece',
    military_tag: 'Military Tag',
    encrypted_drive: 'Encrypted Drive',
    outpost_badge: 'Outpost Badge',
    sheet_metal: 'Sheet Metal',
    large_crate_splinter: 'Large Crate Splinter',
    loose_bearings: 'Loose Bearings',
    conveyor_belt_scrap: 'Conveyor Belt Scrap',
    storage_label_roll: 'Storage Label Roll',
    broken_loader_arm: 'Broken Loader Arm',
    data_fragment: 'Data Fragment',
    broken_masonry: 'Broken Masonry',
    iron_strut: 'Iron Strut',
    worn_banner_cloth: 'Worn Banner Cloth',
    reinforced_iron_plate: 'Reinforced Iron Plate',
    ancient_relief_fragment: 'Ancient Relief Fragment',
    royal_seal: 'Royal Seal',
    ornate_chest_plate: 'Ornate Chest Plate (Broken)',

    // TIER 4
    engine_scrap: 'Engine Scrap',
    belt_hose_parts: 'Belt & Hose Parts',
    electronic_fragments: 'Electronic Fragments',
    intact_spark_unit: 'Intact Spark Unit',
    reinforced_gear: 'Reinforced Gear',
    vehicle_data_core: 'Vehicle Data Core',
    prototype_motor_part: 'Prototype Motor Part',
    alloy_plates: 'Alloy Plates',
    power_coil: 'Power Coil',
    metal_tubing: 'Metal Tubing',
    hydraulic_rod: 'Hydraulic Rod',
    spark_blueprint_fragment: 'Spark Blueprint Fragment',
    reactor_shard: 'Reactor Shard',
    stabilized_core_fragment: 'Stabilized Core Fragment',
    lab_scrap: 'Lab Scrap',
    broken_analyzer: 'Broken Analyzer',
    crystalized_data_powder: 'Crystalized Data Powder',
    intact_sensor: 'Intact Sensor',
    precursor_alloy: 'Precursor Alloy',
    biometric_keycard: 'Biometric Keycard',
    miniature_energy_cell: 'Miniature Energy Cell',
    advanced_circuitry: 'Advanced Circuitry',
    tech_casing: 'Tech Casing',
    hardened_plate: 'Hardened Plate',
    power_regulator: 'Power Regulator',
    cooling_module: 'Cooling Module',
    ai_data_node: 'AI Data Node',
    tech_core: 'Tech Core',

    // TIER 5
    hyperalloy_scrap: 'Hyperalloy Scrap',
    quantum_flux_cable: 'Quantum Flux Cable',
    stabilized_crystal_shard: 'Stabilized Crystal Shard',
    isotope_regulator: 'Isotope Regulator',
    chrono_stamped_plate: 'Chrono-Stamped Plate',
    quantum_memory_lattice: 'Quantum Memory Lattice',
    quantum_core: 'Quantum Core',

    // Fishing items
    fish_shrimp: 'Shrimp',
    fish_minnow: 'Minnow',
    fish_sardine: 'Sardine',
    fish_small_crab: 'Small Crab',
    fish_anchovy: 'Anchovy',
    fish_bass: 'Bass',
    fish_catfish: 'Catfish',
    fish_carp: 'Carp',
    fish_trout: 'Trout',
    fish_salmon: 'Salmon',
    fish_pike: 'Pike',
    fish_mackerel: 'Mackerel',
    fish_snapper: 'Snapper',
    fish_sea_bass: 'Sea Bass',
    fish_eel: 'Eel',
    fish_swordfish_young: 'Young Swordfish',
    fish_tuna: 'Tuna',
    fish_marlin: 'Marlin',
    fish_giant_eel: 'Giant Eel',
    fish_shark: 'Shark',
    fish_leviathan: 'Deep-Sea Leviathan',
    fish_abyssal_lanternfish: 'Abyssal Lanternfish',
    fish_elder_turtle: 'Elder Turtle',
    fish_cosmic_carp: 'Cosmic Carp',

    // -- MINING ITEMS --
    small_stone: 'Small Stone',
    cracked_pebble: 'Cracked Pebble',
    rough_flint: 'Rough Flint',
    dull_shard: 'Dull Shard',
    limestone_chunk: 'Limestone Chunk',
    chalk_dust: 'Chalk Dust',
    fossil_fragment: 'Fossil Fragment',
    ancient_shell: 'Ancient Shell',
    coal: 'Coal',
    dense_coal: 'Dense Coal',
    volatile_ember: 'Volatile Ember',
    ember_core: 'Ember Core',
    copper_ore: 'Copper Ore',
    malachite_chip: 'Malachite Chip',
    copper_nugget: 'Copper Nugget',
    pure_copper_node: 'Pure Copper Node',
    tin_ore: 'Tin Ore',
    cassiterite_shard: 'Cassiterite Shard',
    tin_nugget: 'Tin Nugget',
    smelters_lump: 'Smelter’s Lump',
    iron_ore: 'Iron Ore',
    hematite_chunk: 'Hematite Chunk',
    iron_nugget: 'Iron Nugget',
    pure_iron_crystal: 'Pure Iron Crystal',
    saltpeter: 'Saltpeter',
    nitric_compound: 'Nitric Compound',
    mineral_crystal: 'Mineral Crystal',
    stabilized_powder: 'Stabilized Powder',
    silver_ore: 'Silver Ore',
    native_silver: 'Native Silver',
    polished_silver_chip: 'Polished Silver Chip',
    silver_spirit_token: 'Silver Spirit Token',
    gold_ore: 'Gold Ore',
    gold_flake: 'Gold Flake',
    gold_nugget: 'Gold Nugget',
    pure_gold_ingot: 'Pure Gold Ingot (Raw)',
    ancient_gold_sigil: 'Ancient Gold Sigil',
    quartz_crystal: 'Quartz Crystal',
    shimmer_dust: 'Shimmer Dust',
    prism_shard: 'Prism Shard',
    radiant_crystal: 'Radiant Crystal',
    obsidian_chunk: 'Obsidian Chunk',
    shattered_blade_glass: 'Shattered Blade Glass',
    black_shard: 'Black Shard',
    volcanic_heart: 'Volcanic Heart',
    mithril_ore: 'Mithril Ore',
    refined_mithril_chip: 'Refined Mithril Chip',
    mithril_nugget: 'Mithril Nugget',
    living_mithril_core: 'Living Mithril Core',
    rough_sapphire: 'Rough Sapphire',
    sapphire_shard: 'Sapphire Shard',
    polished_sapphire: 'Polished Sapphire',
    heart_of_the_tides: 'Heart of the Tides',
    rough_ruby: 'Rough Ruby',
    ruby_fragment: 'Ruby Fragment',
    polished_ruby: 'Polished Ruby',
    ember_core_ruby: 'Ember Core Ruby',
    titanium_ore: 'Titanium Ore',
    titanium_shard: 'Titanium Shard',
    reinforced_titan_plate: 'Reinforced Titan Plate',
    titanheart_alloy: 'Titanheart Alloy',
    rough_emerald: 'Rough Emerald',
    emerald_flake: 'Emerald Flake',
    polished_emerald: 'Polished Emerald',
    verdant_core: 'Verdant Core',
    starsteel_ore: 'Starsteel Ore',
    meteoric_fragment: 'Meteoric Fragment',
    celestial_alloy: 'Celestial Alloy',
    fallen_star_core: 'Fallen Star Core',
    mana_crystal: 'Mana Crystal',
    arcane_shard: 'Arcane Shard',
    pure_mana_node: 'Pure Mana Node',
    crystalized_spell_core: 'Crystalized Spell Core',
    precursor_alloy: 'Precursor Alloy',
    alloy_chip: 'Alloy Chip',
    stabilized_tech_plate: 'Stabilized Tech Plate',
    ancient_power_core: 'Ancient Power Core',
    quantum_crystal: 'Quantum Crystal',
    phase_shard: 'Phase Shard',
    temporal_fragment: 'Temporal Fragment',
    quantum_singularity_core: 'Quantum Singularity Core',

    // Legacy / Other (Mapped to match new names if needed or kept)
    scrap_metal: 'Scrap Metal',
    torn_cloth: 'Torn Cloth',
    bottle_caps: 'Bottle Caps',
    ancient_scrap: 'Ancient Scrap',
    old_gears: 'Old Gears',
    mysterious_orb: 'Mysterious Orb',
    circuit_board: 'Circuit Board',
    power_core: 'Power Core',
    broken_chip: 'Broken Chip',
    drone_parts: 'Drone Parts',
    mech_plating: 'Mech Plating',
    lab_components: 'Lab Components',
    quantum_components: 'Quantum Components',
    automaton_core: 'Automaton Core',
    research_data: 'Research Data Cache',
    star_tech: 'Star-Era Tech Relic'
};

export const ITEM_ICONS = {
    log_birch: 'item_log_birch.png',
    log_pine: 'item_log_pine.png',
    log_poplar: 'item_log_poplar.png',
    log_alder: 'item_log_alder.png',
    log_cedar: 'item_log_cedar.png',
    log_elm: 'item_log_elm.png',
    log_chestnut: 'item_log_chestnut.png',
    log_beech: 'item_log_beech.png',
    log_ash: 'item_log_ash.png',
    log_walnut: 'item_log_walnut.png',
    log_sycamore: 'item_log_sycamore.png',
    log_hornbeam: 'item_log_hornbeam.png',
    log_yew: 'item_log_yew.png',
    log_cherry: 'item_log_cherry.png',
    log_ebony: 'item_log_ebony.png',
    log_olive: 'item_log_olive.png',
    log_ironwood: 'item_log_ironwood.png',
    log_black_locust: 'item_log_black_locust.png',
    log_dragonfir: 'item_log_dragonfir.png',
    log_world_oak: 'item_log_world_oak.png',
    log_oak: 'item_log_oak.png',
    log_willow: 'item_log_willow.png',
    log_maple: 'item_log_maple.png',

    // -- MINING ICONS --
    // TIER 1
    small_stone: 'item_stone_fragments.png',
    cracked_pebble: 'item_stone_fragments.png',
    rough_flint: 'item_stone_fragments.png',
    dull_shard: 'item_stone_fragments.png',
    limestone_chunk: 'item_stone_fragments.png',
    chalk_dust: 'item_cosmic_dust.png',
    fossil_fragment: 'item_ancient_scrap.png',
    ancient_shell: 'item_ancient_scrap.png',
    coal: 'item_coal.png',
    dense_coal: 'item_coal.png',
    volatile_ember: 'item_burnt_coil.png',
    ember_core: 'item_burnt_coil.png',

    // TIER 2
    copper_ore: 'item_ore_copper.png',
    malachite_chip: 'item_small_gem_chip.png',
    copper_nugget: 'item_ore_copper.png',
    pure_copper_node: 'item_ore_copper.png',
    tin_ore: 'item_ore_iron.png',
    cassiterite_shard: 'item_small_gem_chip.png',
    tin_nugget: 'item_ore_iron.png',
    smelters_lump: 'item_ore_iron.png',
    iron_ore: 'item_ore_iron.png',
    hematite_chunk: 'item_ore_iron.png',
    iron_nugget: 'item_ore_iron.png',
    pure_iron_crystal: 'item_small_gem_chip.png',
    saltpeter: 'item_cosmic_dust.png',
    nitric_compound: 'item_cosmic_dust.png',
    mineral_crystal: 'item_small_gem_chip.png',
    stabilized_powder: 'item_cosmic_dust.png',

    // TIER 3
    silver_ore: 'item_ore_iron.png',
    native_silver: 'item_ore_iron.png',
    polished_silver_chip: 'item_small_gem_chip.png',
    silver_spirit_token: 'item_ancient_coin.png',
    gold_ore: 'item_ore_gold.png',
    gold_flake: 'item_small_gem_chip.png',
    gold_nugget: 'item_ore_gold.png',
    pure_gold_ingot: 'item_ore_gold.png',
    ancient_gold_sigil: 'item_ancient_coin.png',
    quartz_crystal: 'item_small_gem_chip.png',
    shimmer_dust: 'item_cosmic_dust.png',
    prism_shard: 'item_glass_shards.png',
    radiant_crystal: 'item_small_gem_chip.png',
    obsidian_chunk: 'item_coal.png',
    shattered_blade_glass: 'item_glass_shards.png',
    black_shard: 'item_glass_shards.png',
    volcanic_heart: 'item_gem_ruby.png',

    // TIER 4
    mithril_ore: 'item_ore_mithril.png',
    refined_mithril_chip: 'item_ore_mithril.png',
    mithril_nugget: 'item_ore_mithril.png',
    living_mithril_core: 'item_power_core.png',
    rough_sapphire: 'item_gem_sapphire.png',
    sapphire_shard: 'item_gem_sapphire.png',
    polished_sapphire: 'item_gem_sapphire.png',
    heart_of_the_tides: 'item_mysterious_orb.png',
    rough_ruby: 'item_gem_ruby.png',
    ruby_fragment: 'item_gem_ruby.png',
    polished_ruby: 'item_gem_ruby.png',
    ember_core_ruby: 'item_gem_ruby.png',
    titanium_ore: 'item_ore_mithril.png',
    titanium_shard: 'item_ore_mithril.png',
    reinforced_titan_plate: 'item_mech_plating.png',
    titanheart_alloy: 'item_unknown_alloy.png',
    rough_emerald: 'item_gem_sapphire.png',
    emerald_flake: 'item_gem_sapphire.png',
    polished_emerald: 'item_gem_sapphire.png',
    verdant_core: 'item_mysterious_orb.png',

    // TIER 5
    starsteel_ore: 'item_ore_mithril.png',
    meteoric_fragment: 'item_stone_fragments.png',
    celestial_alloy: 'item_unknown_alloy.png',
    fallen_star_core: 'item_star_tech.png',
    mana_crystal: 'item_mysterious_orb.png',
    arcane_shard: 'item_singularity_shards.png',
    pure_mana_node: 'item_mysterious_orb.png',
    crystalized_spell_core: 'item_mysterious_orb.png',
    precursor_alloy: 'item_unknown_alloy.png',
    alloy_chip: 'item_broken_chip.png',
    stabilized_tech_plate: 'item_mech_plating.png',
    ancient_power_core: 'item_automaton_core.png',
    quantum_crystal: 'item_singularity_shards.png',
    phase_shard: 'item_singularity_shards.png',
    temporal_fragment: 'item_singularity_shards.png',
    quantum_singularity_core: 'item_singularity_shards.png',

    // SCAVENGING - TIER 1
    scrap_metal_bits: 'item_scrap_metal.png',
    frayed_wire: 'item_frayed_wire.png',
    plastic_shards: 'item_plastic_shards.png',
    rusted_bolt: 'item_rusted_bolt.png',
    bent_spoon: 'item_bent_spoon.png',
    lost_coin: 'item_lost_coin.png',
    stone_fragments: 'item_stone_fragments.png',
    cracked_tile: 'item_cracked_tile.png',
    rusted_nails: 'item_rusted_nails.png',
    broken_tool_handle: 'item_broken_tool_handle.png',
    intact_brick: 'item_intact_brick.png',
    small_gem_chip: 'item_small_gem_chip.png',

    // SCAVENGING - TIER 2
    scrap_metal_plate: 'item_scrap_metal_plate.png',
    copper_wire: 'item_copper_wire.png',
    gear_fragment: 'item_gear_fragment.png',
    small_spring: 'item_small_spring.png',
    intact_gear: 'item_intact_gear.png',
    broken_servo: 'item_broken_servo.png',
    slick_sludge: 'item_slick_sludge.png',
    waterlogged_scrap: 'item_waterlogged_scrap.png',
    moldy_cloth: 'item_moldy_cloth.png',
    corroded_battery: 'item_corroded_battery.png',
    intact_fuse: 'item_intact_fuse.png',
    old_pendant: 'item_old_pendant.png',
    mixed_scrap: 'item_mixed_scrap.png',
    glass_shards: 'item_glass_shards.png',
    metal_pipe_chunk: 'item_metal_pipe_chunk.png',
    broken_circuit_board: 'item_broken_circuit_board.png',
    intact_container: 'item_intact_container.png',
    ancient_coin: 'item_ancient_coin.png',
    recovered_trinket: 'item_recovered_trinket.png',

    // NEW SCAVENGING ICONS
    camera_lens: 'item_camera_lens.png',
    small_battery: 'item_small_battery.png',
    concrete_chunk: 'item_concrete_chunk.png',
    rebar_fragment: 'item_rebar_fragment.png',
    old_rations: 'item_old_rations.png',
    ammo_casing: 'item_ammo_casing.png',
    plasma_residue: 'item_plasma_residue.png',
    burnt_coil: 'item_burnt_coil.png',
    heat_sink: 'item_heat_sink.png',
    satellite_dish: 'item_satellite_dish.png',
    solar_panel_shard: 'item_solar_panel_shard.png',
    vacuum_sealed_pouch: 'item_vacuum_sealed_pouch.png',
    cosmic_dust: 'item_cosmic_dust.png',
    alien_glyph: 'item_alien_glyph.png',
    unknown_alloy: 'item_unknown_alloy.png',
    singularity_shards: 'item_singularity_shards.png',

    // SCAVENGING - TIER 3
    wood_scraps: 'item_wood_scraps.png',
    rusted_hinges: 'item_rusted_hinges.png',
    fabric_scraps: 'item_fabric_scraps.png',
    intact_lock: 'item_intact_lock.png',
    polished_stone: 'item_polished_stone.png',
    old_journal_page: 'item_old_journal_page.png',
    strange_key: 'item_strange_key.png',
    metal_panel: 'item_metal_panel.png',
    wire_bundle: 'item_wire_bundle.png',
    reinforced_bolts: 'item_reinforced_bolts.png',
    structural_beam_piece: 'item_structural_beam_piece.png',
    military_tag: 'item_military_tag.png',
    encrypted_drive: 'item_encrypted_drive.png',
    outpost_badge: 'item_outpost_badge.png',
    sheet_metal: 'item_sheet_metal.png',
    large_crate_splinter: 'item_large_crate_splinter.png',
    loose_bearings: 'item_loose_bearings.png',
    conveyor_belt_scrap: 'item_conveyor_belt_scrap.png',
    storage_label_roll: 'item_storage_label_roll.png',
    broken_loader_arm: 'item_broken_loader_arm.png',
    data_fragment: 'item_data_fragment.png',
    broken_masonry: 'item_broken_masonry.png',
    iron_strut: 'item_iron_strut.png',
    worn_banner_cloth: 'item_worn_banner_cloth.png',
    reinforced_iron_plate: 'item_reinforced_iron_plate.png',
    ancient_relief_fragment: 'item_ancient_relief_fragment.png',
    royal_seal: 'item_royal_seal.png',
    ornate_chest_plate: 'item_ornate_chest_plate.png',

    // SCAVENGING - TIER 4
    engine_scrap: 'item_engine_scrap.png',
    belt_hose_parts: 'item_belt_hose_parts.png',
    electronic_fragments: 'item_electronic_fragments.png',
    intact_spark_unit: 'item_intact_spark_unit.png',
    reinforced_gear: 'item_reinforced_gear.png',
    vehicle_data_core: 'item_vehicle_data_core.png',
    prototype_motor_part: 'item_prototype_motor_part.png',
    alloy_plates: 'item_alloy_plates.png',
    power_coil: 'item_power_coil.png',
    metal_tubing: 'item_metal_tubing.png',
    hydraulic_rod: 'item_hydraulic_rod.png',
    spark_blueprint_fragment: 'item_spark_blueprint_fragment.png',
    reactor_shard: 'item_reactor_shard.png',
    stabilized_core_fragment: 'item_stabilized_core_fragment.png',
    lab_scrap: 'item_lab_scrap.png',
    broken_analyzer: 'item_broken_analyzer.png',
    crystalized_data_powder: 'item_crystalized_data_powder.png',
    intact_sensor: 'item_intact_sensor.png',
    precursor_alloy: 'item_precursor_alloy.png',
    biometric_keycard: 'item_biometric_keycard.png',
    miniature_energy_cell: 'item_miniature_energy_cell.png',
    advanced_circuitry: 'item_advanced_circuitry.png',
    tech_casing: 'item_tech_casing.png',
    hardened_plate: 'item_hardened_plate.png',
    power_regulator: 'item_power_regulator.png',
    cooling_module: 'item_cooling_module.png',
    ai_data_node: 'item_ai_data_node.png',
    tech_core: 'item_tech_core.png',

    // SCAVENGING - TIER 5
    hyperalloy_scrap: 'item_hyperalloy_scrap.png',
    quantum_flux_cable: 'item_quantum_flux_cable.png',
    stabilized_crystal_shard: 'item_stabilized_crystal_shard.png',
    isotope_regulator: 'item_isotope_regulator.png',
    chrono_stamped_plate: 'item_chrono_stamped_plate.png',
    quantum_memory_lattice: 'item_quantum_memory_lattice.png',
    quantum_core: 'item_quantum_core.png',

    // Fishing icons
    fish_shrimp: 'item_fish_shrimp.png',
    fish_minnow: 'item_fish_minnow.png',
    fish_sardine: 'item_fish_sardine.png',
    fish_small_crab: 'item_fish_small_crab.png',
    fish_anchovy: 'item_fish_anchovy.png',
    fish_bass: 'item_fish_bass.png',
    fish_catfish: 'item_fish_catfish.png',
    fish_carp: 'item_fish_carp.png',
    fish_trout: 'item_fish_trout.png',
    fish_salmon: 'item_fish_salmon.png',
    fish_pike: 'item_fish_pike.png',
    fish_mackerel: 'item_fish_mackerel.png',
    fish_snapper: 'item_fish_snapper.png',
    fish_sea_bass: 'item_fish_sea_bass.png',
    fish_eel: 'item_fish_eel.png',
    fish_swordfish_young: 'item_fish_swordfish_young.png',
    fish_tuna: 'item_fish_tuna.png',
    fish_marlin: 'item_fish_marlin.png',
    fish_giant_eel: 'item_fish_giant_eel.png',
    fish_shark: 'item_fish_shark.png',
    fish_leviathan: 'item_fish_leviathan.png',
    fish_abyssal_lanternfish: 'item_fish_abyssal_lanternfish.png',
    fish_elder_turtle: 'item_fish_elder_turtle.png',
    fish_cosmic_carp: 'item_fish_cosmic_carp.png',
    scrap_metal: 'item_scrap_metal.png',
    torn_cloth: 'item_torn_cloth.png',
    bottle_caps: 'item_bottle_caps.png',
    ancient_scrap: 'item_ancient_scrap.png',
    old_gears: 'item_old_gears.png',
    mysterious_orb: 'item_mysterious_orb.png',
    circuit_board: 'item_circuit_board.png',
    power_core: 'item_power_core.png',
    broken_chip: 'item_broken_chip.png',
    drone_parts: 'item_drone_parts.png',
    mech_plating: 'item_mech_plating.png',
    lab_components: 'item_lab_components.png',
    quantum_components: 'item_quantum_components.png',
    automaton_core: 'item_automaton_core.png',
    research_data: 'item_research_data.png',
    star_tech: 'item_star_tech.png'
};